stages:
  - deploy

deploy:
  stage: deploy
  script:
    - pip install -r requirements.txt
    - python data_ingestion/fetch_data_reddit.py
    - python data_transformation/transform_data.py
    - uvicorn api.app:app --host 0.0.0.0 --port 8000
